script:
  - travis_retry node_modules/.bin/gulp

env:
  - JS2COFFEE=2.0.0 DIALECT=mysql SEQUELIZE=3.30.4
  - JS2COFFEE=2.0.0 DIALECT=postgres SEQUELIZE=4.1.0

sudo: required
dist: trusty

language: node_js

node_js:
  - "4.0"
  - "6.0"

cache:
  directories:
    - node_modules

before_script:
  # mount ramdisk
  - "sudo mkdir /mnt/sequelize-ramdisk"
  - "sudo mount -t ramfs tmpfs /mnt/sequelize-ramdisk"
  # setup docker
  - "docker-compose up -d ${dialect}"
  - "if [ $DIALECT = 'mysql' ]; then docker run --link ${DIALECT}:db -e CHECK_PORT=3306 -e CHECK_HOST=db --net sequelize_default giorgos/takis; fi"
  - "if [ $DIALECT = 'postgres' ]; then docker run --link ${DIALECT}:db -e CHECK_PORT=5432 -e CHECK_HOST=db --net sequelize_default giorgos/takis; fi"
  - npm install js2coffee@$(echo $JS2COFFEE)
  - npm install sequelize@$(echo $SEQUELIZE)
