script:
  - travis_retry node_modules/.bin/gulp

env:
  - JS2COFFEE=2.0.0 DIALECT=mysql SEQUELIZE=3.30.4
  - JS2COFFEE=2.0.0 DIALECT=postgres SEQUELIZE=4.1.0

sudo: required
dist: trusty

language: node_js

node_js:
  - "4.0"
  - "6.0"

cache:
  directories:
    - node_modules

before_script:
  # mount ramdisk
  - "if [ $POSTGRES_VER ] || [ $MYSQL_VER ]; then sudo mkdir /mnt/sequelize-ramdisk; fi"
  - "if [ $POSTGRES_VER ] || [ $MYSQL_VER ]; then sudo mount -t ramfs tmpfs /mnt/sequelize-ramdisk; fi"
  # setup docker
  - "if [ $POSTGRES_VER ] || [ $MYSQL_VER ]; then docker-compose up -d ${POSTGRES_VER} ${MYSQL_VER}; fi"
  - "if [ $MYSQL_VER ]; then docker run --link ${MYSQL_VER}:db -e CHECK_PORT=3306 -e CHECK_HOST=db --net sequelize_default giorgos/takis; fi"
  - "if [ $POSTGRES_VER ]; then docker run --link ${POSTGRES_VER}:db -e CHECK_PORT=5432 -e CHECK_HOST=db --net sequelize_default giorgos/takis; fi"
